### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by Jailbreak7587** [cankatmis/layered-CRUD-application#1]
- [x] GitHub repository is created with the correct naming scheme
- [x] the lab teacher's GitHub user was invited to the repository
- [x] the empty projects are created
- [x] .gitignore file was modified
- [x] .mdf and .ldf files are created in the Data layer
- [x] the last three steps were committed and pushed to the remote repository (visible at GitHub's web UI)

Hello,

In the project requirements you can find the following: 

> In the root, 3 folders must be created by clicking on the solution’s name and Add new folders from the Visual Studio’s solution explorer. Then, after the folders created via drag-n-drop method the previously created projects should be moved accordingly to this:
> 
> - Backend (Data, Endpoint, Logic, Repository, Test)
> - Frontend (Client)
> - Shared (Models)

This part is missing, or you might have created the folders in the default solution explorer view, you can switch to the other view via the button that is next to the home icon (it has a visual studio icon inside of it) there you can create the folders and move the projects, the solution should be pretty smart about updating the paths to the projects.

Roland

**Comment by Jailbreak7587** [comment]
In that case, you can remove the projects from visual studio inside the regular solution explorer  with right click remove (since they can't be loaded anyway, this shouldn't delete anything just remove the project) then you can add them as an existing project: right click on solution -> add -> existing project

**Comment by Jailbreak7587** [comment]
You probably won't be the only person who will have issues with this, so I will show how you can fix this issue at the beginning of this week's lesson, that way everyone should know how to do it, you can continue along with the project without this fix in the meantime it shouldn't be an issue.
